version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: make install
      - save_cache:
          key: deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: make test
      - run:
          name: Compile
          command: yarn build
  publish:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Login to npm
          command: npm config set "//registry.npmjs.org/:_authToken" $NPM_AUTH
      - run:
          name: Publish to npm
          command: npm publish .
workflows:
  version: 2
  test_and_publish:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /v?[0-9]+(\.[0-9]+)*(-.+)?/
            branches:
              ignore: /.*/
